version: "3.9"

networks:
  refactor_net:
    driver: bridge

services:
  api:
    build: ./backend
    env_file:
      - .env
    networks:
      - refactor_net
    volumes:
      - ./code_workspace:/app/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
      - mcp_fs
      - mcp_shell
      - mcp_scan

    

  redis:
    image: redis:7-alpine
    networks:
      - refactor_net
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    networks:
      - refactor_net
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"

  mcp_fs:
    build: ./tools/mcp_fs
    networks:
      - refactor_net
    volumes:
      - ./code_workspace:/code
    ports:
      - "3901:8000"

  mcp_shell:
    build: ./tools/mcp_shell
    networks:
      - refactor_net
    volumes:
      - ./code_workspace:/code
    ports:
      - "3902:8000"

  mcp_scan:
    build: ./tools/mcp_scan
    networks:
      - refactor_net
    volumes:
      - ./code_workspace:/code
    ports:
      - "3903:8000"

  frontend:
    build: ./frontend
    env_file:
      - .env
    networks:
      - refactor_net
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  ollama_models:
